### ISSUE TITLE
code

### ISSUE THREAD

**Issue by huliangxiao** [lihaoliu-cambridge/mtmr-net#2]
hello, i'm confused about the code below, the dateset don't provide the csv and pkl file

1. file_list = glob(original_data_path + "Images_3/" + "*.mhd")
2. csv_info = pd.read_csv(os.path.join(original_csvfiles_path, "CSVFILES", "annotations_xml_voxel.csv"))
3. f = open("/home/lhliu/Onepiece/project/PythonProjects/bmdiagnosis_research/data/"
             "output_data/preprocessing_related/LIDC_mask_all.pkl")

please tell where is wrong, thanks a lot!

**Comment by lihaoliu-cambridge** [comment]
It is a middle file which is produced during the data generating stage.

This file contains information of all lung nodules from the original xml file .

Please see https://github.com/jcausey-astate/NoduleX_code for generating the datasets from the original datas.

**Comment by huliangxiao** [comment]
thanks, i'll try~

**Comment by huliangxiao** [comment]
does the csv_and_feature_file_tools folder generate the .csv and .pkl file?
and what is the *mhd? i don't find the code.

sorry for bothering, but i really need ur help.

**Comment by lihaoliu-cambridge** [comment]
No,  the .mhd file is the 3D volume preprocessed from the original LIDC-IDRI dataset.

These files are generated by my own preprocessing code which is modified based on NoduleX's code.

I think you can follow this part from NoduleX directly since I cannot find my data generating codes.

Besides, you can modify that code to create your own.

It is basically a process that crops small lung nodules from the entire body (3D volumes) and records its benign-malignancy and other information in a csv file.

**Comment by huliangxiao** [comment]
ok, thank you!

**Comment by shuyao-zhang** [comment]
hello，im confused about “LIDC_mask_all.pkl” 
This code exists in the preprocessing phase，where can i generate this .pkl file？perhaps ，where can i download this file？
I would like to know the processing relationship between each folder.
i really need your help,thank you very much!

**Comment by lihaoliu-cambridge** [comment]
This is a generated middle-stage data by me. It contains the information about the lung nodules.

I have remove it from the project in GitHub since I am not allow to redistribute data.

Those information can be found in original datasets.

Please follow the given links for data preprocessing.
